# Generated by Django 3.0.7 on 2020-07-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='recipes/')),
                ('long_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Category')),
            ],
            options={
                'verbose_name': 'Hekaye',
                'verbose_name_plural': 'Hekayeler',
                'ordering': ('created_at',),
            },
        ),
    ]
