# Generated by Django 3.0.7 on 2020-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('created_at',), 'verbose_name': 'Resept', 'verbose_name_plural': 'Reseptlər'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='long_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
