# Generated by Django 3.0.7 on 2020-07-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='min_read_time',
            field=models.PositiveIntegerField(default=1, verbose_name='Min read time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='min_read_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Min read time'),
            preserve_default=False,
        ),
    ]
