# Generated by Django 3.0.7 on 2020-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20200720_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='min_read_time',
            field=models.PositiveIntegerField(editable=False, verbose_name='Min read time'),
        ),
        migrations.AlterField(
            model_name='story',
            name='min_read_time',
            field=models.PositiveIntegerField(editable=False, verbose_name='Min read time'),
        ),
    ]
